### ISSUE TITLE
SFTP Connection error

### ISSUE THREAD

**Issue by abalasr** [ArjenLammers/sftp-connector#10]
Getting following error while connecting to SFTP(latest version). Not using "Strick Hostkey checking" and "use key"
net.schmizz.sshj.transport.TransportException: Server closed connection during identification exchange
	at net.schmizz.sshj.transport.TransportImpl.init(TransportImpl.java:181)
	at net.schmizz.sshj.SSHClient.onConnect(SSHClient.java:769)
	at net.schmizz.sshj.SocketClient.connect(SocketClient.java:127)
	at sftp.impl.SFTP.connect(SFTP.java:269)
	at sftp.actions.Connect.executeAction(Connect.java:53)
	at sftp.actions.Connect.executeAction(Connect.java:29)
	at com.mendix.systemwideinterfaces.core.UserAction.execute(UserAction.java:46)
	at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.doCall(CoreActionHandlerImpl.scala:71)
	at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.call(CoreActionHandlerImpl.scala:48)
	at com.mendix.core.actionmanagement.internal.InternalCoreAction.call(InternalCoreAction.scala:25)
	at com.mendix.basis.actionmanagement.ActionManager.$anonfun$executeSync$2(ActionManager.scala:80)
	at com.mendix.util.classloading.Runner.withContextClassLoader(Runner.java:19)
	at com.mendix.basis.actionmanagement.ActionManager.executeSync(ActionManager.scala:79)
	at com.mendix.basis.actionmanagement.UserActionCallBuilderImpl.execute(UserActionCallBuilderImpl.scala:34)
	at com.mendix.modules.microflowengine.actions.actioncall.ForegroundJavaAction.doExecute(ForegroundJavaAction.scala:35)
	at com.mendix.modules.microflowengine.actions.actioncall.ForegroundJavaAction.doExecute(ForegroundJavaAction.scala:11)
	at com.mendix.modules.microflowengine.actions.actioncall.JavaAction.execute(JavaAction.scala:38)
	at com.mendix.modules.microflowengine.microflow.impl.MicroflowObject.$anonfun$execute$1(MicroflowObject.scala:32)
	at scala.Option.flatMap(Option.scala:283)
	at com.mendix.modules.microflowengine.microflow.impl.MicroflowObject.execute(MicroflowObject.scala:29)
	at com.mendix.modules.microflowengine.microflow.impl.MicroflowImpl.$anonfun$executeAfterBreakingIfNecessary$2(MicroflowImpl.scala:167)
	at scala.Option.flatMap(Option.scala:283)
	at com.mendix.modules.microflowengine.microflow.impl.MicroflowImpl.executeAfterBreakingIfNecessary(MicroflowImpl.scala:167)
	at com.mendix.modules.microflowengine.microflow.impl.MicroflowImpl.executeAction(MicroflowImpl.scala:114)
	at com.mendix.systemwideinterfaces.core.UserAction.execute(UserAction.java:46)
	at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.doCall(CoreActionHandlerImpl.scala:71)
	at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.call(CoreActionHandlerImpl.scala:48)
	at com.mendix.core.actionmanagement.internal.InternalCoreAction.call(InternalCoreAction.scala:25)
	at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.$anonfun$runMonitoredAction$1(CoreActionHandlerImpl.scala:59)
	at com.mendix.basis.actionmanagement.ActionMonitoring$.$anonfun$monitor$1(ActionMonitoring.scala:49)
	at com.mendix.util.classloading.Runner.withContextClassLoader(Runner.java:19)
	at com.mendix.basis.actionmanagement.ActionMonitoring$.monitor(ActionMonitoring.scala:49)
	at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.runMonitoredAction(CoreActionHandlerImpl.scala:59)
	at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.call(CoreActionHandlerImpl.scala:46)
	at com.mendix.core.actionmanagement.internal.InternalCoreAction.call(InternalCoreAction.scala:25)
	at com.mendix.basis.actionmanagement.ActionManager.$anonfun$executeAsync$3(ActionManager.scala:64)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:672)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:431)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

Caused by: net.schmizz.sshj.transport.TransportException: Server closed connection during identification exchange
	at net.schmizz.sshj.transport.TransportImpl.receiveServerIdent(TransportImpl.java:201)
	at net.schmizz.sshj.transport.TransportImpl.init(TransportImpl.java:174)
	at net.schmizz.sshj.SSHClient.onConnect(SSHClient.java:769)
	at net.schmizz.sshj.SocketClient.connect(SocketClient.java:127)
	at sftp.impl.SFTP.connect(SFTP.java:269)
	at sftp.actions.Connect.executeAction(Connect.java:53)
	at sftp.actions.Connect.executeAction(Connect.java:29)
	at com.mendix.systemwideinterfaces.core.UserAction.execute(UserAction.java:46)
	at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.doCall(CoreActionHandlerImpl.scala:71)
	at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.call(CoreActionHandlerImpl.scala:48)
	at com.mendix.core.actionmanagement.internal.InternalCoreAction.call(InternalCoreAction.scala:25)
	at com.mendix.basis.actionmanagement.ActionManager.$anonfun$executeSync$2(ActionManager.scala:80)
	at com.mendix.util.classloading.Runner.withContextClassLoader(Runner.java:19)
	at com.mendix.basis.actionmanagement.ActionManager.executeSync(ActionManager.scala:79)
	at com.mendix.basis.actionmanagement.UserActionCallBuilderImpl.execute(UserActionCallBuilderImpl.scala:34)
	at com.mendix.modules.microflowengine.actions.actioncall.ForegroundJavaAction.doExecute(ForegroundJavaAction.scala:35)
	at com.mendix.modules.microflowengine.actions.actioncall.ForegroundJavaAction.doExecute(ForegroundJavaAction.scala:11)
	at com.mendix.modules.microflowengine.actions.actioncall.JavaAction.execute(JavaAction.scala:38)
	at com.mendix.modules.microflowengine.microflow.impl.MicroflowObject.$anonfun$execute$1(MicroflowObject.scala:32)
	at scala.Option.flatMap(Option.scala:283)
	at com.mendix.modules.microflowengine.microflow.impl.MicroflowObject.execute(MicroflowObject.scala:29)
	at com.mendix.modules.microflowengine.microflow.impl.MicroflowImpl.$anonfun$executeAfterBreakingIfNecessary$2(MicroflowImpl.scala:167)
	at scala.Option.flatMap(Option.scala:283)
	at com.mendix.modules.microflowengine.microflow.impl.MicroflowImpl.executeAfterBreakingIfNecessary(MicroflowImpl.scala:167)
	at com.mendix.modules.microflowengine.microflow.impl.MicroflowImpl.executeAction(MicroflowImpl.scala:114)
	at com.mendix.systemwideinterfaces.core.UserAction.execute(UserAction.java:46)
	at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.doCall(CoreActionHandlerImpl.scala:71)
	at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.call(CoreActionHandlerImpl.scala:48)
	at com.mendix.core.actionmanagement.internal.InternalCoreAction.call(InternalCoreAction.scala:25)
	at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.$anonfun$runMonitoredAction$1(CoreActionHandlerImpl.scala:59)
	at com.mendix.basis.actionmanagement.ActionMonitoring$.$anonfun$monitor$1(ActionMonitoring.scala:49)
	at com.mendix.util.classloading.Runner.withContextClassLoader(Runner.java:19)
	at com.mendix.basis.actionmanagement.ActionMonitoring$.monitor(ActionMonitoring.scala:49)
	at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.runMonitoredAction(CoreActionHandlerImpl.scala:59)
	at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.call(CoreActionHandlerImpl.scala:46)
	at com.mendix.core.actionmanagement.internal.InternalCoreAction.call(InternalCoreAction.scala:25)
	at com.mendix.basis.actionmanagement.ActionManager.$anonfun$executeAsync$3(ActionManager.scala:64)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:672)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:431)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by ArjenLammers** [comment]
hi abalasr,
this means that somewhere during identification the server disconnected.
the exact reason will probably be in the server logs.
you could enabling debug level log messages and that might give you a hint.

good luck.
