### ISSUE TITLE
Error when calling Put action.

### ISSUE THREAD

**Issue by TJonkhoff** [ArjenLammers/sftp-connector#11]
Hello im getting an error in mendix when trying to put a file. But if i check the directory with filezilla the file is there.
Does anyone know how to fix this. Here is the error.

Er heeft zich een fout voorgedaan tijdens het uploaden van het bestand: UnsupportedOperation: This operation is currently unsupported.
Details: com.mendix.systemwideinterfaces.MendixRuntimeException: net.schmizz.sshj.sftp.SFTPException: UnsupportedOperation: This operation is currently unsupported.
at SFTP.SFTP_Put (JavaAction : 'Put file')
at {"name":"SFTP.Connect","type":"JavaAction"}
at SFTP.IVK_Put (JavaAction : 'Upload file')

Advanced stacktrace:
at com.mendix.modules.microflowengine.MicroflowUtil.processException(MicroflowUtil.java:83)

Caused by:
com.mendix.systemwideinterfaces.MendixRuntimeException: net.schmizz.sshj.sftp.SFTPException: UnsupportedOperation: This operation is currently unsupported.
at com.mendix.modules.microflowengine.MicroflowUtil.processException(MicroflowUtil.java:83)

Caused by:
net.schmizz.sshj.sftp.SFTPException: UnsupportedOperation: This operation is currently unsupported.
at com.mendix.modules.microflowengine.MicroflowUtil.processException(MicroflowUtil.java:83)

Caused by:
UnsupportedOperation: This operation is currently unsupported.
at com.mendix.modules.microflowengine.MicroflowUtil.processException(MicroflowUtil.java:83)

**Comment by ArjenLammers** [comment]
This is probably caused by an operation performed by the underlying library and your SSH server not allowing it.
Could you enable logging (LogLibraryLogging) and provide the detailed information about where it's running into an error?

**Comment by TJonkhoff** [comment]
Im sorry im trying to get LibraryLogging enabled but i dont understand where i can find the logs. And what the classpath in the AddLibraryLogListener action should be. If you could explain to me how to enable this correctly i can get back to you.

![image](https://user-images.githubusercontent.com/77490451/158387702-552cb93f-5784-4009-b74b-74638eb2fd6d.png)

**Comment by TJonkhoff** [comment]
I got the log.

com.mendix.storage.FileNotFoundInStorageException: LocalFileSystemStore:: File does not exist for key: 0
	at com.mendix.storage.localfilesystem.internal.LocalFileSystemStore.getFileDocumentAsFile(LocalFileSystemStore.scala:167)
	at com.mendix.storage.localfilesystem.internal.LocalFileSystemStore.$anonfun$doRetrieveWith$1(LocalFileSystemStore.scala:147)
	at scala.util.Try$.apply(Try.scala:210)
	at com.mendix.storage.localfilesystem.internal.LocalFileSystemStore.doRetrieveWith(LocalFileSystemStore.scala:146)
	at com.mendix.storage.localfilesystem.internal.LocalFileSystemStore.doRetrieve(LocalFileSystemStore.scala:137)
	at com.mendix.storage.StorageService.retrieve(StorageService.scala:90)
	at com.mendix.storage.StorageService.retrieve$(StorageService.scala:89)
	at com.mendix.storage.localfilesystem.internal.LocalFileSystemStore.retrieve(LocalFileSystemStore.scala:25)
	at com.mendix.filedocumentprocessor.internal.FileDocumentProcessorImpl.getFileDocument(FileDocumentProcessorImpl.java:67)
	at com.mendix.basis.component.FileDocumentCore.getFileDocumentContent(FileDocumentCore.scala:15)
	at com.mendix.basis.component.FileDocumentCore.getFileDocumentContent$(FileDocumentCore.scala:11)
	at com.mendix.basis.component.InternalCore.getFileDocumentContent(InternalCore.scala:21)
	at com.mendix.core.Core.getFileDocumentContent(Core.java:1190)
	at sftp.impl.SFTP.validateKey(SFTP.java:113)
	at sftp.actions.ProcessKey.executeAction(ProcessKey.java:34)
	at sftp.actions.ProcessKey.executeAction(ProcessKey.java:17)
	at com.mendix.systemwideinterfaces.core.UserAction.execute(UserAction.java:46)
	at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.doCall(CoreActionHandlerImpl.scala:71)
	at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.call(CoreActionHandlerImpl.scala:48)
	at com.mendix.core.actionmanagement.internal.InternalCoreAction.call(InternalCoreAction.scala:25)
	at com.mendix.basis.actionmanagement.ActionManager.$anonfun$executeSync$2(ActionManager.scala:80)
	at com.mendix.util.classloading.Runner.withContextClassLoader(Runner.java:19)
	at com.mendix.basis.actionmanagement.ActionManager.executeSync(ActionManager.scala:79)
	at com.mendix.basis.actionmanagement.UserActionCallBuilderImpl.execute(UserActionCallBuilderImpl.scala:34)
	at com.mendix.modules.microflowengine.actions.actioncall.ForegroundJavaAction.doExecute(ForegroundJavaAction.scala:35)
	at com.mendix.modules.microflowengine.actions.actioncall.ForegroundJavaAction.doExecute(ForegroundJavaAction.scala:11)
	at com.mendix.modules.microflowengine.actions.actioncall.JavaAction.execute(JavaAction.scala:38)
	at com.mendix.modules.microflowengine.microflow.impl.MicroflowObject.$anonfun$execute$1(MicroflowObject.scala:32)
	at scala.Option.flatMap(Option.scala:283)
	at com.mendix.modules.microflowengine.microflow.impl.MicroflowObject.execute(MicroflowObject.scala:29)
	at com.mendix.modules.microflowengine.microflow.impl.MicroflowImpl.$anonfun$executeAfterBreakingIfNecessary$2(MicroflowImpl.scala:167)
	at scala.Option.flatMap(Option.scala:283)
	at com.mendix.modules.microflowengine.microflow.impl.MicroflowImpl.executeAfterBreakingIfNecessary(MicroflowImpl.scala:167)
	at com.mendix.modules.microflowengine.microflow.impl.MicroflowImpl.executeAction(MicroflowImpl.scala:114)
	at com.mendix.systemwideinterfaces.core.UserAction.execute(UserAction.java:46)
	at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.doCall(CoreActionHandlerImpl.scala:71)
	at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.call(CoreActionHandlerImpl.scala:48)
	at com.mendix.core.actionmanagement.internal.InternalCoreAction.call(InternalCoreAction.scala:25)
	at com.mendix.basis.actionmanagement.ActionManager.$anonfun$executeSync$2(ActionManager.scala:80)
	at com.mendix.util.classloading.Runner.withContextClassLoader(Runner.java:19)
	at com.mendix.basis.actionmanagement.ActionManager.executeSync(ActionManager.scala:79)
	at com.mendix.basis.actionmanagement.SyncEventExtendedAction.$anonfun$executeBeforeActionsSync$2(SyncEventExtendedAction.scala:46)
	at com.mendix.basis.actionmanagement.SyncEventExtendedAction.$anonfun$executeBeforeActionsSync$2$adapted(SyncEventExtendedAction.scala:44)
	at scala.collection.IterableOnceOps.forall(IterableOnce.scala:577)
	at scala.collection.IterableOnceOps.forall$(IterableOnce.scala:574)
	at scala.collection.AbstractIterable.forall(Iterable.scala:919)
	at com.mendix.basis.actionmanagement.SyncEventExtendedAction.$anonfun$executeBeforeActionsSync$1(SyncEventExtendedAction.scala:44)
	at com.mendix.basis.actionmanagement.SyncEventExtendedAction.$anonfun$executeBeforeActionsSync$1$adapted(SyncEventExtendedAction.scala:40)
	at scala.collection.IterableOnceOps.forall(IterableOnce.scala:577)
	at scala.collection.IterableOnceOps.forall$(IterableOnce.scala:574)
	at scala.collection.AbstractIterable.forall(Iterable.scala:919)
	at com.mendix.basis.actionmanagement.SyncEventExtendedAction.executeBeforeActionsSync(SyncEventExtendedAction.scala:40)
	at com.mendix.basis.actionmanagement.SyncEventExtendedAction.executeAction(SyncEventExtendedAction.scala:25)
	at com.mendix.basis.actionmanagement.EventExtendedAction.execute(EventExtendedAction.java:94)
	at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.doCall(CoreActionHandlerImpl.scala:71)
	at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.call(CoreActionHandlerImpl.scala:48)
	at com.mendix.core.actionmanagement.internal.InternalCoreAction.call(InternalCoreAction.scala:25)
	at com.mendix.basis.actionmanagement.ActionManager.$anonfun$executeSync$2(ActionManager.scala:81)
	at com.mendix.util.classloading.Runner.withContextClassLoader(Runner.java:19)
	at com.mendix.basis.actionmanagement.ActionManager.executeSync(ActionManager.scala:79)
	at com.mendix.basis.actionmanagement.ActionManager.$anonfun$executeInTransactionSync$1(ActionManager.scala:91)
	at scala.util.Try$.apply(Try.scala:210)
	at com.mendix.basis.actionmanagement.ActionManager.executeInTransactionSync(ActionManager.scala:91)
	at com.mendix.basis.component.TransactionCore.$anonfun$storeObjectsAndAutoCommittedObjects$1(TransactionCore.scala:190)
	at scala.collection.immutable.List.map(List.scala:246)
	at scala.collection.immutable.List.map(List.scala:79)
	at com.mendix.basis.component.TransactionCore.storeObjectsAndAutoCommittedObjects(TransactionCore.scala:188)
	at com.mendix.basis.component.TransactionCore.commit(TransactionCore.scala:126)
	at com.mendix.basis.component.TransactionCore.commit$(TransactionCore.scala:109)
	at com.mendix.basis.component.InternalCore.commit(InternalCore.scala:21)
	at com.mendix.basis.component.TransactionCore.commitWithEvents(TransactionCore.scala:69)
	at com.mendix.basis.component.TransactionCore.commit(TransactionCore.scala:28)
	at com.mendix.basis.component.TransactionCore.commit$(TransactionCore.scala:27)
	at com.mendix.basis.component.InternalCore.commit(InternalCore.scala:21)
	at com.mendix.basis.component.TransactionCore.commit(TransactionCore.scala:23)
	at com.mendix.basis.component.TransactionCore.commit$(TransactionCore.scala:23)
	at com.mendix.basis.component.InternalCore.commit(InternalCore.scala:21)
	at com.mendix.modules.microflowengine.actions.mxobject.ChangeItemsExecutor.executeChanges(ChangeItemsExecutor.scala:34)
	at com.mendix.modules.microflowengine.actions.mxobject.ChangeItemsExecutor.executeChanges$(ChangeItemsExecutor.scala:20)
	at com.mendix.modules.microflowengine.actions.mxobject.ChangeAction.executeChanges(ChangeAction.scala:12)
	at com.mendix.modules.microflowengine.actions.mxobject.CreateChangeAction$$anonfun$1.applyOrElse(CreateChangeAction.scala:26)
	at com.mendix.modules.microflowengine.actions.mxobject.CreateChangeAction$$anonfun$1.applyOrElse(CreateChangeAction.scala:24)
	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:313)
	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:309)
	at scala.Option.collect(Option.scala:462)
	at com.mendix.modules.microflowengine.actions.mxobject.CreateChangeAction.execute(CreateChangeAction.scala:24)
	at com.mendix.modules.microflowengine.actions.mxobject.CreateChangeAction.execute(CreateChangeAction.scala:12)
	at com.mendix.modules.microflowengine.microflow.impl.MicroflowObject.$anonfun$execute$1(MicroflowObject.scala:32)
	at scala.Option.flatMap(Option.scala:283)
	at com.mendix.modules.microflowengine.microflow.impl.MicroflowObject.execute(MicroflowObject.scala:29)
	at com.mendix.modules.microflowengine.microflow.impl.MicroflowImpl.$anonfun$executeAfterBreakingIfNecessary$2(MicroflowImpl.scala:167)
	at scala.Option.flatMap(Option.scala:283)
	at com.mendix.modules.microflowengine.microflow.impl.MicroflowImpl.executeAfterBreakingIfNecessary(MicroflowImpl.scala:167)
	at com.mendix.modules.microflowengine.microflow.impl.MicroflowImpl.executeAction(MicroflowImpl.scala:114)
	at com.mendix.systemwideinterfaces.core.UserAction.execute(UserAction.java:46)
	at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.doCall(CoreActionHandlerImpl.scala:71)
	at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.call(CoreActionHandlerImpl.scala:48)
	at com.mendix.core.actionmanagement.internal.InternalCoreAction.call(InternalCoreAction.scala:25)
	at com.mendix.basis.actionmanagement.ActionManager.$anonfun$executeSync$2(ActionManager.scala:80)
	at com.mendix.util.classloading.Runner.withContextClassLoader(Runner.java:19)
	at com.mendix.basis.actionmanagement.ActionManager.executeSync(ActionManager.scala:79)
	at com.mendix.basis.actionmanagement.MicroflowCallBuilderImpl.execute(MicroflowCallBuilderImpl.scala:38)
	at com.mendix.webui.actions.client.RetrieveAction.retrieveAllByMicroflow(RetrieveAction.scala:114)
	at com.mendix.webui.actions.client.RetrieveAction.$anonfun$apply$3(RetrieveAction.scala:53)
	at scala.util.Either.map(Either.scala:382)
	at com.mendix.webui.actions.client.RetrieveAction.apply(RetrieveAction.scala:43)
	at com.mendix.webui.actions.client.RetrieveAction.apply(RetrieveAction.scala:28)
	at com.mendix.webui.actions.client.RegularClientAction$Helpers$.$anonfun$liftEither$1(RegularClientAction.scala:29)
	at com.mendix.webui.actions.client.RegularClientAction$Helpers$StateHandler.$anonfun$apply$4(RegularClientAction.scala:55)
	at com.mendix.webui.requesthandling.helpers.StateHandling.withState(StateHandling.scala:42)
	at com.mendix.webui.requesthandling.helpers.StateHandling.withState$(StateHandling.scala:39)
	at com.mendix.webui.actions.client.RegularClientAction$Helpers$StateHandler.withState(RegularClientAction.scala:45)
	at com.mendix.webui.actions.client.RegularClientAction$Helpers$StateHandler.apply(RegularClientAction.scala:53)
	at com.mendix.webui.actions.client.RegularClientAction$Helpers$StateHandler.apply(RegularClientAction.scala:45)
	at com.mendix.webui.actions.client.RegularClientAction.$anonfun$execute$3(RegularClientAction.scala:109)
	at scala.util.Try$.apply(Try.scala:210)
	at com.mendix.webui.actions.client.RegularClientAction.$anonfun$execute$2(RegularClientAction.scala:109)
	at com.mendix.webui.actions.client.RegularClientAction.$anonfun$execute$2$adapted(RegularClientAction.scala:107)
	at com.mendix.webui.requesthandling.helpers.ContextHandling.$anonfun$inContext$5(ContextHandling.scala:51)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at com.mendix.basis.actionmanagement.ActionMonitoring$.$anonfun$monitor$1(ActionMonitoring.scala:49)
	at com.mendix.util.classloading.Runner.withContextClassLoader(Runner.java:19)
	at com.mendix.basis.actionmanagement.ActionMonitoring$.monitor(ActionMonitoring.scala:49)
	at com.mendix.webui.requesthandling.helpers.ContextHandling.inContext(ContextHandling.scala:51)
	at com.mendix.webui.requesthandling.helpers.ContextHandling.inContext$(ContextHandling.scala:26)
	at com.mendix.webui.actions.client.RegularClientAction.inContext(RegularClientAction.scala:86)
	at com.mendix.webui.requesthandling.helpers.ContextHandling.inContext(ContextHandling.scala:23)
	at com.mendix.webui.requesthandling.helpers.ContextHandling.inContext$(ContextHandling.scala:18)
	at com.mendix.webui.actions.client.RegularClientAction.inContext(RegularClientAction.scala:86)
	at com.mendix.webui.actions.client.RegularClientAction.$anonfun$execute$1(RegularClientAction.scala:107)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at com.mendix.webui.requesthandling.helpers.ProfileHandling.profileRequest(ProfileHandling.scala:14)
	at com.mendix.webui.requesthandling.helpers.ProfileHandling.profileRequest$(ProfileHandling.scala:10)
	at com.mendix.webui.actions.client.RegularClientAction.profileRequest(RegularClientAction.scala:86)
	at com.mendix.webui.actions.client.RegularClientAction.execute(RegularClientAction.scala:104)
	at com.mendix.webui.requesthandling.ClientRequestHandler.handleAction(ClientRequestHandler.scala:106)
	at com.mendix.webui.requesthandling.ClientRequestHandler.processRequest(ClientRequestHandler.scala:79)
	at com.mendix.externalinterface.connector.RequestHandler.doProcessRequest(RequestHandler.java:35)
	at com.mendix.external.connector.MxRuntimeConnector.$anonfun$processRequest$1(MxRuntimeConnector.scala:51)
	at com.mendix.external.connector.MxRuntimeConnector.$anonfun$processRequest$1$adapted(MxRuntimeConnector.scala:51)
	at com.mendix.util.classloading.Runner.withContextClassLoader(Runner.java:19)
	at com.mendix.external.connector.MxRuntimeConnector.processRequest(MxRuntimeConnector.scala:51)
	at com.mendix.basis.impl.MxRuntimeImplBase.processRequest(MxRuntimeImplBase.java:827)
	at com.mendix.m2ee.appcontainer.server.handler.RuntimeServlet.service(RuntimeServlet.scala:25)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1626)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:228)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:386)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by TJonkhoff** [comment]
Here are the logs there are no error logs just info. So i cant see where the error occurs. It is inside the put action tho.

net.schmizz.sshj.transport.random.BouncyCastleRandom - Generating random seed from SecureRandom.

net.schmizz.sshj.transport.TransportImpl - Client identity string: SSH-2.0-SSHJ_0.27.0

net.schmizz.sshj.transport.TransportImpl - Server identity string: SSH-2.0-AzureSSH_1.0.0

net.schmizz.sshj.connection.channel.direct.SessionChannel - Will request `sftp` subsystem

net.schmizz.sshj.transport.TransportImpl - Disconnected - BY_APPLICATION

net.schmizz.sshj.transport.random.BouncyCastleRandom - Generating random seed from SecureRandom.

net.schmizz.sshj.transport.TransportImpl - Client identity string: SSH-2.0-SSHJ_0.27.0

net.schmizz.sshj.transport.TransportImpl - Server identity string: SSH-2.0-AzureSSH_1.0.0

net.schmizz.sshj.connection.channel.direct.SessionChannel - Will request `sftp` subsystem

net.schmizz.sshj.transport.TransportImpl - Disconnected - BY_APPLICATION

net.schmizz.sshj.transport.random.BouncyCastleRandom - Generating random seed from SecureRandom.

net.schmizz.sshj.transport.TransportImpl - Client identity string: SSH-2.0-SSHJ_0.27.0

net.schmizz.sshj.transport.TransportImpl - Server identity string: SSH-2.0-AzureSSH_1.0.0

net.schmizz.sshj.connection.channel.direct.SessionChannel - Will request `sftp` subsystem

net.schmizz.sshj.transport.TransportImpl - Disconnected - BY_APPLICATION

**Comment by TLFinley** [comment]
I am getting the same issue.  Has there been any resolution to this issue?  The exact same error message is happening and like he said the file is getting downloaded to the server.  I am able to do all other SFTP functions like delete and create directory without any issue.  It is just the PUT that is throwing the exception.
