### ISSUE TITLE
Error when obtaining hostkey in version 2.9.0

### ISSUE THREAD

**Issue by dvthoenderdaal** [ArjenLammers/sftp-connector#18]
I upgraded the Mendix SFTP module form version 2.6.0 to 2.9.0. I took care of older jar files and on my local development environment the exact same configured connections as in production work just fine. Authorization is done with username / password and obtaining a new host key works fine. But, unfortunately not on my customers (on-premise) test environment. Here the existing connections can not connect anymore and I get below message. I build a package of the development version and deployed it on the test environment. I see the exact same userlibs in development and test and no older or other jar version. So obtaining the new host key fails suddenly. Anyone an idea?

com.mendix.webui.WebUIException: Exception while executing runtime operation
	at com.mendix.webui.actions.client.RuntimeOperationAction.$anonfun$apply$1(RuntimeOperationAction.scala:62)

Caused by: com.mendix.modules.microflowengine.MicroflowException: com.mendix.systemwideinterfaces.MendixRuntimeException: net.schmizz.sshj.transport.TransportException: X25519 unsupported public key length [46]
	at SFTP.IVK_ObtainHostkey (JavaAction : 'Get host key')

Advanced stacktrace:
	at com.mendix.modules.microflowengine.MicroflowUtil.processException(MicroflowUtil.java:83)

Caused by: com.mendix.core.CoreRuntimeException: com.mendix.systemwideinterfaces.MendixRuntimeException: net.schmizz.sshj.transport.TransportException: X25519 unsupported public key length [46]
	at com.mendix.basis.actionmanagement.ActionManager.executeSync(ActionManager.scala:110)

Caused by: com.mendix.systemwideinterfaces.MendixRuntimeException: net.schmizz.sshj.transport.TransportException: X25519 unsupported public key length [46]
	at com.mendix.util.classloading.Runner$.withContextClassLoader(Runner.scala:23)

Caused by: net.schmizz.sshj.transport.TransportException: X25519 unsupported public key length [46]
	at net.schmizz.sshj.transport.TransportException$1.chain(TransportException.java:33)
	at net.schmizz.sshj.transport.TransportException$1.chain(TransportException.java:27)
	at net.schmizz.concurrent.Promise.deliverError(Promise.java:95)
	at net.schmizz.concurrent.Event.deliverError(Event.java:74)
	at net.schmizz.concurrent.ErrorDeliveryUtil.alertEvents(ErrorDeliveryUtil.java:34)
	at net.schmizz.sshj.transport.KeyExchanger.notifyError(KeyExchanger.java:460)
	at net.schmizz.sshj.transport.TransportImpl.die(TransportImpl.java:602)
	at net.schmizz.sshj.transport.Reader.run(Reader.java:66)

Caused by: net.schmizz.sshj.common.SSHException: X25519 unsupported public key length [46]
	at net.schmizz.sshj.common.SSHException$1.chain(SSHException.java:37)
	at net.schmizz.sshj.common.SSHException$1.chain(SSHException.java:30)
	at net.schmizz.sshj.transport.TransportImpl.die(TransportImpl.java:597)
	at net.schmizz.sshj.transport.Reader.run(Reader.java:66)

Caused by: java.lang.IllegalArgumentException: X25519 unsupported public key length [46]
	at net.schmizz.sshj.transport.kex.Curve25519DH.setPublicKey(Curve25519DH.java:93)
	at net.schmizz.sshj.transport.kex.Curve25519DH.init(Curve25519DH.java:78)
	at net.schmizz.sshj.transport.kex.Curve25519SHA256.initDH(Curve25519SHA256.java:59)
	at net.schmizz.sshj.transport.kex.AbstractDHG.init(AbstractDHG.java:46)
	at net.schmizz.sshj.transport.KeyExchanger.gotKexInit(KeyExchanger.java:280)
	at net.schmizz.sshj.transport.KeyExchanger.handle(KeyExchanger.java:424)
	at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:496)
	at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:113)
	at net.schmizz.sshj.transport.Decoder.received(Decoder.java:200)
	at net.schmizz.sshj.transport.Reader.run(Reader.java:60)

**Comment by dvthoenderdaal** [comment]
Sorry for creating this issue. The cause for this issue is the usage of an older JDK 11 version. If you use JDK 11.0.24 for instance everything works great.

**Comment by dvthoenderdaal** [comment]
Sorry for creating this issue. The cause for this issue is the usage of an older JDK 11 version. If you use JDK 11.0.24 for instance everything works great.

**Comment by ArjenLammers** [comment]
hi @dvthoenderdaal great to see you managed to find the cause and thanks for sharing!
