### ISSUE TITLE
Unable to connect: null cannot connect with UN/PW

### ISSUE THREAD

**Issue by MiniMaxi-user** [ArjenLammers/sftp-connector#7]
Hi Arjen,

In MX 8.16.0 I have configured a connection with only username/password. 
In filezilla everything works fine but via this sftp-connector in mendix I get an error:
Can you help me?
TNX 

Martijn

Unable to connect: null
Details: com.mendix.systemwideinterfaces.MendixRuntimeException: java.lang.NullPointerException
at com.mendix.basis.actionmanagement.ActionManagerBase.executeSync(ActionManagerBase.java:156)

Caused by:
java.lang.NullPointerException
at com.mendix.util.classloading.Runner.doRunUsingClassLoaderOf(Runner.java:30)

Caused by:
null
at net.schmizz.sshj.transport.verification.FingerprintVerifier.getInstance(FingerprintVerifier.java:52)
at net.schmizz.sshj.SSHClient.addHostKeyVerifier(SSHClient.java:188)
at sftp.actions.Connect.executeAction(Connect.java:69)
at sftp.actions.Connect.executeAction(Connect.java:41)
at com.mendix.systemwideinterfaces.core.UserAction.execute(UserAction.java:46)
at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.doCall(CoreActionHandlerImpl.scala:71)
at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.call(CoreActionHandlerImpl.scala:49)
at com.mendix.core.actionmanagement.CoreAction.call(CoreAction.java:54)
at com.mendix.basis.actionmanagement.ActionManagerBase$1.execute(ActionManagerBase.java:147)
at com.mendix.util.classloading.Runner.doRunUsingClassLoaderOf(Runner.java:26)
at com.mendix.basis.actionmanagement.ActionManagerBase.executeSync(ActionManagerBase.java:152)
at com.mendix.basis.actionmanagement.UserActionCallBuilderImpl.execute(UserActionCallBuilderImpl.scala:30)
at com.mendix.modules.microflowengine.actions.actioncall.JavaAction.execute(JavaAction.scala:56)
at com.mendix.modules.microflowengine.microflow.impl.MicroflowObject.$anonfun$execute$1(MicroflowObject.scala:32)
at scala.Option.flatMap(Option.scala:283)
at com.mendix.modules.microflowengine.microflow.impl.MicroflowObject.execute(MicroflowObject.scala:29)
at com.mendix.modules.microflowengine.microflow.impl.MicroflowImpl.$anonfun$executeAfterBreakingIfNecessary$2(MicroflowImpl.scala:174)
at scala.Option.flatMap(Option.scala:283)
at com.mendix.modules.microflowengine.microflow.impl.MicroflowImpl.executeAfterBreakingIfNecessary(MicroflowImpl.scala:174)
at com.mendix.modules.microflowengine.microflow.impl.MicroflowImpl.executeAction(MicroflowImpl.scala:121)
at com.mendix.systemwideinterfaces.core.UserAction.execute(UserAction.java:46)
at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.doCall(CoreActionHandlerImpl.scala:71)
at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.call(CoreActionHandlerImpl.scala:49)
at com.mendix.core.actionmanagement.CoreAction.call(CoreAction.java:54)
at com.mendix.basis.actionmanagement.DefaultActionMonitor$.$anonfun$run$1(CustomMonitoredAction.scala:18)
at com.mendix.basis.actionmanagement.IMonitoredAction$$anon$1.execute(IMonitoredAction.scala:47)
at com.mendix.util.classloading.Runner.doRunUsingClassLoaderOf(Runner.java:26)
at com.mendix.basis.actionmanagement.IMonitoredAction.monitor(IMonitoredAction.scala:49)
at com.mendix.basis.actionmanagement.IMonitoredAction.monitor$(IMonitoredAction.scala:25)
at com.mendix.basis.actionmanagement.CustomMonitoredAction.monitor(CustomMonitoredAction.scala:22)
at com.mendix.basis.actionmanagement.DefaultActionMonitor$.run(CustomMonitoredAction.scala:18)
at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.runMonitoredAction(CoreActionHandlerImpl.scala:60)
at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.call(CoreActionHandlerImpl.scala:47)
at com.mendix.core.actionmanagement.CoreAction.call(CoreAction.java:54)
at com.mendix.basis.actionmanagement.ActionManager.$anonfun$execute$1(ActionManager.scala:118)
at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:671)
at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:430)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by MiniMaxi-user** [comment]
My fault! I forgot to set the Host key fingerprint.
