### ISSUE TITLE
TransportException: Socket closed when getting files

### ISSUE THREAD

**Issue by eevers-avisi** [ArjenLammers/sftp-connector#9]
While trying to get files using the sftp connector I encountered the following issue (stacktrace beneath). This issue won't show up when getting files of 2mb, but does show up when getting larger files (already at files of 5mb). What causes this problem? I'm currently using version 2.3 of the connector

`
Socket closed
Details: com.mendix.systemwideinterfaces.MendixRuntimeException: net.schmizz.sshj.transport.TransportException: Socket closed
at SFTP.SFTP_Get (JavaAction : 'Get file')
at {"name":"SFTP.Connect","type":"JavaAction"}
at SFTP.IVK_Open (JavaAction : 'Connect')

Advanced stacktrace:
at com.mendix.modules.microflowengine.MicroflowUtil.processException(MicroflowUtil.java:85)

Caused by:
com.mendix.systemwideinterfaces.MendixRuntimeException: net.schmizz.sshj.transport.TransportException: Socket closed
at com.mendix.basis.actionmanagement.ActionManager.executeSync(ActionManager.scala:84)

Caused by:
net.schmizz.sshj.transport.TransportException: Socket closed
at com.mendix.util.classloading.Runner.withContextClassLoader(Runner.java:23)

Caused by:
Socket closed
at net.schmizz.sshj.transport.TransportImpl.write(TransportImpl.java:454)
at net.schmizz.sshj.connection.channel.ChannelOutputStream$DataBuffer.flush(ChannelOutputStream.java:102)
at net.schmizz.sshj.connection.channel.ChannelOutputStream$DataBuffer.flush(ChannelOutputStream.java:70)
at net.schmizz.sshj.connection.channel.ChannelOutputStream.flush(ChannelOutputStream.java:182)
at net.schmizz.sshj.sftp.SFTPEngine.transmit(SFTPEngine.java:297)
at net.schmizz.sshj.sftp.SFTPEngine.request(SFTPEngine.java:130)
at net.schmizz.sshj.sftp.RemoteResource.close(RemoteResource.java:53)
at sftp.actions.Get$1.close(Get.java:60)
at com.mendix.storage.StorageService.store(StorageService.scala:32)
at com.mendix.storage.StorageService.store$(StorageService.scala:28)
at com.mendix.storage.localfilesystem.internal.LocalFileSystemStore.store(LocalFileSystemStore.scala:25)
at com.mendix.filedocumentprocessor.internal.FileDocumentProcessorImpl.writeFile(FileDocumentProcessorImpl.java:205)
at com.mendix.filedocumentprocessor.internal.FileDocumentProcessorImpl.storeFileDocument(FileDocumentProcessorImpl.java:130)
at com.mendix.basis.component.FileDocumentCore.storeFileDocumentContent(FileDocumentCore.scala:32)
at com.mendix.basis.component.FileDocumentCore.storeFileDocumentContent$(FileDocumentCore.scala:27)
at com.mendix.basis.component.InternalCore.storeFileDocumentContent(InternalCore.scala:21)
at com.mendix.core.Core.storeFileDocumentContent(Core.java:1200)
at sftp.actions.Get.executeAction(Get.java:66)
at sftp.actions.Get.executeAction(Get.java:29)
at com.mendix.systemwideinterfaces.core.UserAction.execute(UserAction.java:46)
at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.doCall(CoreActionHandlerImpl.scala:70)
at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.call(CoreActionHandlerImpl.scala:48)
at com.mendix.core.actionmanagement.internal.InternalCoreAction.call(InternalCoreAction.scala:25)
at com.mendix.basis.actionmanagement.ActionManager.$anonfun$executeSync$2(ActionManager.scala:80)
at com.mendix.util.classloading.Runner.withContextClassLoader(Runner.java:19)
at com.mendix.basis.actionmanagement.ActionManager.executeSync(ActionManager.scala:79)
at com.mendix.basis.actionmanagement.UserActionCallBuilderImpl.execute(UserActionCallBuilderImpl.scala:35)
at com.mendix.modules.microflowengine.actions.actioncall.ForegroundJavaAction.doExecute(ForegroundJavaAction.scala:35)
at com.mendix.modules.microflowengine.actions.actioncall.ForegroundJavaAction.doExecute(ForegroundJavaAction.scala:11)
at com.mendix.modules.microflowengine.actions.actioncall.JavaAction.execute(JavaAction.scala:38)
at com.mendix.modules.microflowengine.microflow.impl.MicroflowObject.$anonfun$execute$1(MicroflowObject.scala:31)
at scala.Option.flatMap(Option.scala:283)
at com.mendix.modules.microflowengine.microflow.impl.MicroflowObject.execute(MicroflowObject.scala:28)
at com.mendix.modules.microflowengine.microflow.impl.MicroflowImpl.$anonfun$executeAfterBreakingIfNecessary$2(MicroflowImpl.scala:167)
at scala.Option.flatMap(Option.scala:283)
at com.mendix.modules.microflowengine.microflow.impl.MicroflowImpl.executeAfterBreakingIfNecessary(MicroflowImpl.scala:167)
at com.mendix.modules.microflowengine.microflow.impl.MicroflowImpl.executeAction(MicroflowImpl.scala:114)
at com.mendix.systemwideinterfaces.core.UserAction.execute(UserAction.java:46)
at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.doCall(CoreActionHandlerImpl.scala:70)
at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.call(CoreActionHandlerImpl.scala:48)
at com.mendix.core.actionmanagement.internal.InternalCoreAction.call(InternalCoreAction.scala:25)
at com.mendix.basis.actionmanagement.ActionManager.$anonfun$executeSync$2(ActionManager.scala:80)
at com.mendix.util.classloading.Runner.withContextClassLoader(Runner.java:19)
at com.mendix.basis.actionmanagement.ActionManager.executeSync(ActionManager.scala:79)
at com.mendix.basis.actionmanagement.MicroflowCallBuilderImpl.execute(MicroflowCallBuilderImpl.scala:41)
at sftp.actions.Connect.executeAction(Connect.java:79)
at sftp.actions.Connect.executeAction(Connect.java:29)
at com.mendix.systemwideinterfaces.core.UserAction.execute(UserAction.java:46)
at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.doCall(CoreActionHandlerImpl.scala:70)
at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.call(CoreActionHandlerImpl.scala:48)
at com.mendix.core.actionmanagement.internal.InternalCoreAction.call(InternalCoreAction.scala:25)
at com.mendix.basis.actionmanagement.ActionManager.$anonfun$executeSync$2(ActionManager.scala:80)
at com.mendix.util.classloading.Runner.withContextClassLoader(Runner.java:19)
at com.mendix.basis.actionmanagement.ActionManager.executeSync(ActionManager.scala:79)
at com.mendix.basis.actionmanagement.UserActionCallBuilderImpl.execute(UserActionCallBuilderImpl.scala:35)
at com.mendix.modules.microflowengine.actions.actioncall.ForegroundJavaAction.doExecute(ForegroundJavaAction.scala:35)
at com.mendix.modules.microflowengine.actions.actioncall.ForegroundJavaAction.doExecute(ForegroundJavaAction.scala:11)
at com.mendix.modules.microflowengine.actions.actioncall.JavaAction.execute(JavaAction.scala:38)
at com.mendix.modules.microflowengine.microflow.impl.MicroflowObject.$anonfun$execute$1(MicroflowObject.scala:31)
at scala.Option.flatMap(Option.scala:283)
at com.mendix.modules.microflowengine.microflow.impl.MicroflowObject.execute(MicroflowObject.scala:28)
at com.mendix.modules.microflowengine.microflow.impl.MicroflowImpl.$anonfun$executeAfterBreakingIfNecessary$2(MicroflowImpl.scala:167)
at scala.Option.flatMap(Option.scala:283)
at com.mendix.modules.microflowengine.microflow.impl.MicroflowImpl.executeAfterBreakingIfNecessary(MicroflowImpl.scala:167)
at com.mendix.modules.microflowengine.microflow.impl.MicroflowImpl.executeAction(MicroflowImpl.scala:114)
at com.mendix.systemwideinterfaces.core.UserAction.execute(UserAction.java:46)
at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.doCall(CoreActionHandlerImpl.scala:70)
at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.call(CoreActionHandlerImpl.scala:48)
at com.mendix.core.actionmanagement.internal.InternalCoreAction.call(InternalCoreAction.scala:25)
at com.mendix.basis.actionmanagement.ActionManager.$anonfun$executeSync$2(ActionManager.scala:80)
at com.mendix.util.classloading.Runner.withContextClassLoader(Runner.java:19)
at com.mendix.basis.actionmanagement.ActionManager.executeSync(ActionManager.scala:79)
at com.mendix.basis.actionmanagement.MicroflowCallBuilderImpl.execute(MicroflowCallBuilderImpl.scala:41)
at com.mendix.webui.actions.client.ExecuteMicroflowAction.runMicroflow(ExecuteMicroflowAction.scala:76)
at com.mendix.webui.actions.client.ExecuteMicroflowAction.$anonfun$apply$3(ExecuteMicroflowAction.scala:42)
at com.mendix.webui.actions.client.RegularClientAction$Helpers$.$anonfun$liftEither$1(RegularClientAction.scala:29)
at com.mendix.webui.actions.client.RegularClientAction$Helpers$StateHandler.$anonfun$apply$4(RegularClientAction.scala:55)
at com.mendix.webui.requesthandling.helpers.StateHandling.withState(StateHandling.scala:39)
at com.mendix.webui.requesthandling.helpers.StateHandling.withState$(StateHandling.scala:36)
at com.mendix.webui.actions.client.RegularClientAction$Helpers$StateHandler.withState(RegularClientAction.scala:45)
at com.mendix.webui.actions.client.RegularClientAction$Helpers$StateHandler.apply(RegularClientAction.scala:53)
at com.mendix.webui.actions.client.RegularClientAction$Helpers$StateHandler.apply(RegularClientAction.scala:45)
at com.mendix.webui.actions.client.ExecuteMicroflowAction.apply(ExecuteMicroflowAction.scala:43)
at com.mendix.webui.actions.client.ExecuteMicroflowAction.apply(ExecuteMicroflowAction.scala:22)
at com.mendix.webui.actions.client.RegularClientAction.$anonfun$execute$3(RegularClientAction.scala:109)
at scala.util.Try$.apply(Try.scala:210)
at com.mendix.webui.actions.client.RegularClientAction.$anonfun$execute$2(RegularClientAction.scala:109)
at com.mendix.webui.actions.client.RegularClientAction.$anonfun$execute$2$adapted(RegularClientAction.scala:107)
at com.mendix.webui.requesthandling.helpers.ContextHandling.$anonfun$inContext$5(ContextHandling.scala:51)
at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
at com.mendix.basis.actionmanagement.ActionMonitoring$.$anonfun$monitor$1(ActionMonitoring.scala:50)
at com.mendix.util.classloading.Runner.withContextClassLoader(Runner.java:19)
at com.mendix.basis.actionmanagement.ActionMonitoring$.monitor(ActionMonitoring.scala:50)
at com.mendix.webui.requesthandling.helpers.ContextHandling.inContext(ContextHandling.scala:51)
at com.mendix.webui.requesthandling.helpers.ContextHandling.inContext$(ContextHandling.scala:26)
at com.mendix.webui.actions.client.RegularClientAction.inContext(RegularClientAction.scala:86)
at com.mendix.webui.requesthandling.helpers.ContextHandling.inContext(ContextHandling.scala:23)
at com.mendix.webui.requesthandling.helpers.ContextHandling.inContext$(ContextHandling.scala:18)
at com.mendix.webui.actions.client.RegularClientAction.inContext(RegularClientAction.scala:86)
at com.mendix.webui.actions.client.RegularClientAction.$anonfun$execute$1(RegularClientAction.scala:107)
at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
at com.mendix.webui.requesthandling.helpers.ProfileHandling.profileRequest(ProfileHandling.scala:14)
at com.mendix.webui.requesthandling.helpers.ProfileHandling.profileRequest$(ProfileHandling.scala:10)
at com.mendix.webui.actions.client.RegularClientAction.profileRequest(RegularClientAction.scala:86)
at com.mendix.webui.actions.client.RegularClientAction.execute(RegularClientAction.scala:104)
at com.mendix.webui.requesthandling.ClientRequestHandler.handleAction(ClientRequestHandler.scala:106)
at com.mendix.webui.requesthandling.ClientRequestHandler.processRequest(ClientRequestHandler.scala:79)
at com.mendix.externalinterface.connector.RequestHandler.doProcessRequest(RequestHandler.java:35)
at com.mendix.external.connector.MxRuntimeConnector.lambda$processRequest$0(MxRuntimeConnector.java:74)
at com.mendix.util.classloading.Runner.withContextClassLoader(Runner.java:19)
at com.mendix.external.connector.MxRuntimeConnector.processRequest(MxRuntimeConnector.java:73)
at com.mendix.basis.impl.MxRuntimeImplBase.processRequest(MxRuntimeImplBase.java:806)
at com.mendix.m2ee.appcontainer.server.handler.RuntimeServlet.service(RuntimeServlet.scala:25)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:791)
at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1626)
at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:228)
at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1435)
at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
at org.eclipse.jetty.server.Server.handle(Server.java:516)
at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:383)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:882)
at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1036)
at java.base/java.lang.Thread.run(Thread.java:834)

Caused by:
Socket closed
at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113)
at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
at net.schmizz.sshj.transport.TransportImpl.write(TransportImpl.java:451)
at net.schmizz.sshj.connection.channel.ChannelOutputStream$DataBuffer.flush(ChannelOutputStream.java:102)
at net.schmizz.sshj.connection.channel.ChannelOutputStream$DataBuffer.flush(ChannelOutputStream.java:70)
at net.schmizz.sshj.connection.channel.ChannelOutputStream.flush(ChannelOutputStream.java:182)
at net.schmizz.sshj.sftp.SFTPEngine.transmit(SFTPEngine.java:297)
at net.schmizz.sshj.sftp.SFTPEngine.request(SFTPEngine.java:130)
at net.schmizz.sshj.sftp.RemoteResource.close(RemoteResource.java:53)
at sftp.actions.Get$1.close(Get.java:60)
at com.mendix.storage.StorageService.store(StorageService.scala:32)
at com.mendix.storage.StorageService.store$(StorageService.scala:28)
at com.mendix.storage.localfilesystem.internal.LocalFileSystemStore.store(LocalFileSystemStore.scala:25)
at com.mendix.filedocumentprocessor.internal.FileDocumentProcessorImpl.writeFile(FileDocumentProcessorImpl.java:205)
at com.mendix.filedocumentprocessor.internal.FileDocumentProcessorImpl.storeFileDocument(FileDocumentProcessorImpl.java:130)
at com.mendix.basis.component.FileDocumentCore.storeFileDocumentContent(FileDocumentCore.scala:32)
at com.mendix.basis.component.FileDocumentCore.storeFileDocumentContent$(FileDocumentCore.scala:27)
at com.mendix.basis.component.InternalCore.storeFileDocumentContent(InternalCore.scala:21)
at com.mendix.core.Core.storeFileDocumentContent(Core.java:1200)
at sftp.actions.Get.executeAction(Get.java:66)
at sftp.actions.Get.executeAction(Get.java:29)
at com.mendix.systemwideinterfaces.core.UserAction.execute(UserAction.java:46)
at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.doCall(CoreActionHandlerImpl.scala:70)
at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.call(CoreActionHandlerImpl.scala:48)
at com.mendix.core.actionmanagement.internal.InternalCoreAction.call(InternalCoreAction.scala:25)
at com.mendix.basis.actionmanagement.ActionManager.$anonfun$executeSync$2(ActionManager.scala:80)
at com.mendix.util.classloading.Runner.withContextClassLoader(Runner.java:19)
at com.mendix.basis.actionmanagement.ActionManager.executeSync(ActionManager.scala:79)
at com.mendix.basis.actionmanagement.UserActionCallBuilderImpl.execute(UserActionCallBuilderImpl.scala:35)
at com.mendix.modules.microflowengine.actions.actioncall.ForegroundJavaAction.doExecute(ForegroundJavaAction.scala:35)
at com.mendix.modules.microflowengine.actions.actioncall.ForegroundJavaAction.doExecute(ForegroundJavaAction.scala:11)
at com.mendix.modules.microflowengine.actions.actioncall.JavaAction.execute(JavaAction.scala:38)
at com.mendix.modules.microflowengine.microflow.impl.MicroflowObject.$anonfun$execute$1(MicroflowObject.scala:31)
at scala.Option.flatMap(Option.scala:283)
at com.mendix.modules.microflowengine.microflow.impl.MicroflowObject.execute(MicroflowObject.scala:28)
at com.mendix.modules.microflowengine.microflow.impl.MicroflowImpl.$anonfun$executeAfterBreakingIfNecessary$2(MicroflowImpl.scala:167)
at scala.Option.flatMap(Option.scala:283)
at com.mendix.modules.microflowengine.microflow.impl.MicroflowImpl.executeAfterBreakingIfNecessary(MicroflowImpl.scala:167)
at com.mendix.modules.microflowengine.microflow.impl.MicroflowImpl.executeAction(MicroflowImpl.scala:114)
at com.mendix.systemwideinterfaces.core.UserAction.execute(UserAction.java:46)
at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.doCall(CoreActionHandlerImpl.scala:70)
at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.call(CoreActionHandlerImpl.scala:48)
at com.mendix.core.actionmanagement.internal.InternalCoreAction.call(InternalCoreAction.scala:25)
at com.mendix.basis.actionmanagement.ActionManager.$anonfun$executeSync$2(ActionManager.scala:80)
at com.mendix.util.classloading.Runner.withContextClassLoader(Runner.java:19)
at com.mendix.basis.actionmanagement.ActionManager.executeSync(ActionManager.scala:79)
at com.mendix.basis.actionmanagement.MicroflowCallBuilderImpl.execute(MicroflowCallBuilderImpl.scala:41)
at sftp.actions.Connect.executeAction(Connect.java:79)
at sftp.actions.Connect.executeAction(Connect.java:29)
at com.mendix.systemwideinterfaces.core.UserAction.execute(UserAction.java:46)
at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.doCall(CoreActionHandlerImpl.scala:70)
at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.call(CoreActionHandlerImpl.scala:48)
at com.mendix.core.actionmanagement.internal.InternalCoreAction.call(InternalCoreAction.scala:25)
at com.mendix.basis.actionmanagement.ActionManager.$anonfun$executeSync$2(ActionManager.scala:80)
at com.mendix.util.classloading.Runner.withContextClassLoader(Runner.java:19)
at com.mendix.basis.actionmanagement.ActionManager.executeSync(ActionManager.scala:79)
at com.mendix.basis.actionmanagement.UserActionCallBuilderImpl.execute(UserActionCallBuilderImpl.scala:35)
at com.mendix.modules.microflowengine.actions.actioncall.ForegroundJavaAction.doExecute(ForegroundJavaAction.scala:35)
at com.mendix.modules.microflowengine.actions.actioncall.ForegroundJavaAction.doExecute(ForegroundJavaAction.scala:11)
at com.mendix.modules.microflowengine.actions.actioncall.JavaAction.execute(JavaAction.scala:38)
at com.mendix.modules.microflowengine.microflow.impl.MicroflowObject.$anonfun$execute$1(MicroflowObject.scala:31)
at scala.Option.flatMap(Option.scala:283)
at com.mendix.modules.microflowengine.microflow.impl.MicroflowObject.execute(MicroflowObject.scala:28)
at com.mendix.modules.microflowengine.microflow.impl.MicroflowImpl.$anonfun$executeAfterBreakingIfNecessary$2(MicroflowImpl.scala:167)
at scala.Option.flatMap(Option.scala:283)
at com.mendix.modules.microflowengine.microflow.impl.MicroflowImpl.executeAfterBreakingIfNecessary(MicroflowImpl.scala:167)
at com.mendix.modules.microflowengine.microflow.impl.MicroflowImpl.executeAction(MicroflowImpl.scala:114)
at com.mendix.systemwideinterfaces.core.UserAction.execute(UserAction.java:46)
at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.doCall(CoreActionHandlerImpl.scala:70)
at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.call(CoreActionHandlerImpl.scala:48)
at com.mendix.core.actionmanagement.internal.InternalCoreAction.call(InternalCoreAction.scala:25)
at com.mendix.basis.actionmanagement.ActionManager.$anonfun$executeSync$2(ActionManager.scala:80)
at com.mendix.util.classloading.Runner.withContextClassLoader(Runner.java:19)
at com.mendix.basis.actionmanagement.ActionManager.executeSync(ActionManager.scala:79)
at com.mendix.basis.actionmanagement.MicroflowCallBuilderImpl.execute(MicroflowCallBuilderImpl.scala:41)
at com.mendix.webui.actions.client.ExecuteMicroflowAction.runMicroflow(ExecuteMicroflowAction.scala:76)
at com.mendix.webui.actions.client.ExecuteMicroflowAction.$anonfun$apply$3(ExecuteMicroflowAction.scala:42)
at com.mendix.webui.actions.client.RegularClientAction$Helpers$.$anonfun$liftEither$1(RegularClientAction.scala:29)
at com.mendix.webui.actions.client.RegularClientAction$Helpers$StateHandler.$anonfun$apply$4(RegularClientAction.scala:55)
at com.mendix.webui.requesthandling.helpers.StateHandling.withState(StateHandling.scala:39)
at com.mendix.webui.requesthandling.helpers.StateHandling.withState$(StateHandling.scala:36)
at com.mendix.webui.actions.client.RegularClientAction$Helpers$StateHandler.withState(RegularClientAction.scala:45)
at com.mendix.webui.actions.client.RegularClientAction$Helpers$StateHandler.apply(RegularClientAction.scala:53)
at com.mendix.webui.actions.client.RegularClientAction$Helpers$StateHandler.apply(RegularClientAction.scala:45)
at com.mendix.webui.actions.client.ExecuteMicroflowAction.apply(ExecuteMicroflowAction.scala:43)
at com.mendix.webui.actions.client.ExecuteMicroflowAction.apply(ExecuteMicroflowAction.scala:22)
at com.mendix.webui.actions.client.RegularClientAction.$anonfun$execute$3(RegularClientAction.scala:109)
at scala.util.Try$.apply(Try.scala:210)
at com.mendix.webui.actions.client.RegularClientAction.$anonfun$execute$2(RegularClientAction.scala:109)
at com.mendix.webui.actions.client.RegularClientAction.$anonfun$execute$2$adapted(RegularClientAction.scala:107)
at com.mendix.webui.requesthandling.helpers.ContextHandling.$anonfun$inContext$5(ContextHandling.scala:51)
at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
at com.mendix.basis.actionmanagement.ActionMonitoring$.$anonfun$monitor$1(ActionMonitoring.scala:50)
at com.mendix.util.classloading.Runner.withContextClassLoader(Runner.java:19)
at com.mendix.basis.actionmanagement.ActionMonitoring$.monitor(ActionMonitoring.scala:50)
at com.mendix.webui.requesthandling.helpers.ContextHandling.inContext(ContextHandling.scala:51)
at com.mendix.webui.requesthandling.helpers.ContextHandling.inContext$(ContextHandling.scala:26)
at com.mendix.webui.actions.client.RegularClientAction.inContext(RegularClientAction.scala:86)
at com.mendix.webui.requesthandling.helpers.ContextHandling.inContext(ContextHandling.scala:23)
at com.mendix.webui.requesthandling.helpers.ContextHandling.inContext$(ContextHandling.scala:18)
at com.mendix.webui.actions.client.RegularClientAction.inContext(RegularClientAction.scala:86)
at com.mendix.webui.actions.client.RegularClientAction.$anonfun$execute$1(RegularClientAction.scala:107)
at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
at com.mendix.webui.requesthandling.helpers.ProfileHandling.profileRequest(ProfileHandling.scala:14)
at com.mendix.webui.requesthandling.helpers.ProfileHandling.profileRequest$(ProfileHandling.scala:10)
at com.mendix.webui.actions.client.RegularClientAction.profileRequest(RegularClientAction.scala:86)
at com.mendix.webui.actions.client.RegularClientAction.execute(RegularClientAction.scala:104)
at com.mendix.webui.requesthandling.ClientRequestHandler.handleAction(ClientRequestHandler.scala:106)
at com.mendix.webui.requesthandling.ClientRequestHandler.processRequest(ClientRequestHandler.scala:79)
at com.mendix.externalinterface.connector.RequestHandler.doProcessRequest(RequestHandler.java:35)
at com.mendix.external.connector.MxRuntimeConnector.lambda$processRequest$0(MxRuntimeConnector.java:74)
at com.mendix.util.classloading.Runner.withContextClassLoader(Runner.java:19)
at com.mendix.external.connector.MxRuntimeConnector.processRequest(MxRuntimeConnector.java:73)
at com.mendix.basis.impl.MxRuntimeImplBase.processRequest(MxRuntimeImplBase.java:806)
at com.mendix.m2ee.appcontainer.server.handler.RuntimeServlet.service(RuntimeServlet.scala:25)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:791)
at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1626)
at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:228)
at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1435)
at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
at org.eclipse.jetty.server.Server.handle(Server.java:516)
at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:383)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:882)
at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1036)
at java.base/java.lang.Thread.run(Thread.java:834)
`

**Comment by eevers-avisi** [comment]
After running the AfterStartup so logging of the library is redirected to the Mendix log I'm able to see the following, more precise exception:

net.schmizz.sshj.transport.TransportException: Broken transport; encountered EOF
	at net.schmizz.sshj.transport.Reader.run(Reader.java:57)

**Comment by ArjenLammers** [comment]
hi Erik, based on the logging I'm can only conclude the connection between you and the ssh server is lost.
seen the microflow trace, this was a simple action from the explorer with the sftp module, so I don't think there's a previous action interfering with this one.
you could try setting the library logging to debug and perhaps that would give you a better hint. or there might be some server side logging indicating a root cause.

**Comment by eevers-avisi** [comment]
Hi Arjen, after further research it seems like the server I am trying to connect to is closing the connection automatically after a few seconds. So the problem must be there and not in the SFTP connector. Thanks for the given tips to find the problem. I will close the issue now.

**Comment by ArjenLammers** [comment]
hi Erik... one thing I came to, which could be that your connection should be kept alive...
could you try to add the following to /javasource/sftp/impl/SFTP.java at line 269; so it would look like this? (so the ssh.getConnection()... is new)
```

			ssh.connect(configuration.getHostname(), configuration.getPort());
			ssh.getConnection().getKeepAlive().setKeepAliveInterval(15);
			ssh.auth(configuration.getUsername(), authMethods);
```
if this solves your issue, please let me know

**Comment by eevers-avisi** [comment]
Hi Arjen, thanks for the suggestion. The provider who delivers the server I am connecting to, did have issues which were more wide spread. There were more users with the exact same problem. When I saw your suggestion they did already fix the problem. Because of this I didn't actually apply your suggestion, because I think it wouldn't make sense now. The connection is not lost anymore when getting some larger files.

**Comment by ArjenLammers** [comment]
Good to hear. Thanks for the update.
